services:
  api:
    image: ghcr.io/chgr9/rubikcubesolver/cube-rest-api:latest
    pull_policy: always
    container_name: cube-rest-api
    ports:
      - "8181:8080"
    restart: unless-stopped
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./scans:/app/scans
    environment:
      - SPRING_PROFILES_ACTIVE=raspberrypi