services:
  api:
    image: ghcr.io/chgr9/rubikcubesolver/cube-rest-api:latest
    pull_policy: always
    container_name: cube-rest-api
    ports:
      - "8181:8080"
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/media0:/dev/media0
    group_add:
      - "44" # video group
    volumes:
      - ./scans:/app/scans
    environment:
      - UDEV=1
      - SPRING_PROFILES_ACTIVE=raspberrypi