name: Docker Build & Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        cd CubeRestApi
        docker build -t my-spring-app:latest .

    - name: Login to GHCR
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag and Push
      run: |
        # If your repo is "github.com/<owner>/<repo>", you can do:
        docker tag cube-rest-api:latest ghcr.io/${{ github.repository,,}}/cube-rest-api:latest
        
        # Push
        docker push ghcr.io/${{ github.repository,,}}/cube-rest-api:latest
