name: Docker Build & Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push multi-arch
        run: |
          cd CubeRestApi
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/cube-rest-api:latest \
            --push \
            .
